$('.menu-item-1').click(function(){
        $('.item-1').slideToggle();
});
$('.menu-item-2').click(function(){
        $('.item-2').slideToggle();
});
$('.menu-item-3').click(function(){
        $('.item-3').slideToggle();
        });